channels:
  - conda-forge

dependencies:
  - python=3.10.12                # Ensure compatibility with Robocorp's environment
  - pip=23.2.1
  - robocorp-truststore=0.8.0     # Truststore for secure connections
  - pip:
    - rpaframework==28.6.1       # RPA Framework for automation capabilities
    - robocorp-browser==2.3.3     # Browser automation
    - robocorp-windows            # Windows desktop automation
    - robocorp-workitems          # Work items support for passing data between task    
    - pytesseract  # Python bindings for Tesseract OCR
    - Pillow  # For working with images in Python  