channels:
  - conda-forge

dependencies:
  - python=3.10.12                # Ensure compatibility with Robocorp's environment
  - pip=23.2.1
  - robocorp-truststore=0.8.0     # Truststore for secure connections
  - pip:
    - rpaframework==28.0.0        # RPA Framework for automation capabilities
    - robocorp-browser==2.2.1     # Browser automation
    - robocorp-windows            # Windows desktop automation
    - robocorp-workitems          # Work items support for passing data between tasks

# Note: subprocess is part of the Python standard library and does not need to be explicitly installed.
